version: "3"

services:
  db_postgres:
    image: postgres:latest
    container_name: splice_postgres
    ports:
      - "5432:5432"
    networks:
      - splice_network

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: splice
    volumes:
      - $HOME/docker/volumes/splice_postgres:/var/lib/postgresql/data
