"""create_table_order

Revision ID: af25e18d0692
Revises: 9866fb88a518
Create Date: 2025-02-26 00:31:40.978940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af25e18d0692'
down_revision: Union[str, None] = '9866fb88a518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'CASH', 'CRYPTOCURRENCY', 'APPLE_PAY', 'GOOGLE_PAY', 'PIX', name='paymeny_type_enum'), nullable=True),
    sa.Column('has_paid', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('establishment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
